repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-added-large-files
    -   id: check-yaml
        name: Check YAML
    -   id: check-xml
        name: Check XML
-   repo: https://github.com/sirosen/check-jsonschema
    rev: 0.3.1
    hooks:
    -   id: check-github-workflows
    -   id: check-github-actions
-   repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.27.1
    hooks:
    -   id: markdownlint
        name: Test Markdownfiles with markdownlint
-   repo:  https://github.com/jumanjihouse/pre-commit-hooks
    rev:   2.1.5
    hooks:
    -   id: shfmt
        args: ['-w', '-i', '4', '-ci']
    -   id: shellcheck
